IT_PlatForm/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from app01 import views
from django.shortcuts import render,HttpResponse

def qowie(request):
    return HttpResponse("ajlkjhqelkjw")

urlpatterns = [
    #西人马列表
    path("xrm_list/",views.xrm_list,name='xrm_list'),

    path('admin/', admin.site.urls),
    path("index/",views.index,name='index'),
    #项目相关的
    path("add_it/",views.add_it,name='add_it'),
    re_path("edit_it/(?P<pk>\d+)$",views.edit_it,name='edit_it'),
    re_path("delete_it/(?P<pk>\d+)$",views.delete_it,name='delete_it'),
    #接口用例相关
    re_path("add_api/(?P<pk>\d+)$",views.add_api,name='add_api'),
    re_path("api_list/(?P<pk>\d+)$",views.api_list,name='api_list'),
    re_path("edit_api/(?P<pk>\d+)$",views.edit_api,name='edit_api'),
    re_path("delete_api/(?P<pk>\d+)$",views.delete_api,name='delete_api'),
    #用例执行
    re_path("api_run/(?P<pk>\d+)$",views.api_run,name='api_run'),
    #报告下载
    re_path("download_case_report/(?P<pk>\d+)$",views.download_case_report,name='download_case_report'),

    #log日志
    re_path("logs_list/",views.logs_list,name='logs_list'),
    re_path("report_order/(?P<pk>\d+)$",views.report_order,name='report_order'),
    re_path("show_tab/",views.show_tab,name='show_tab'),
    re_path("api_ajax/", views.api_ajax, name='api_ajax'),

]

app01/models.py
from django.db import models


# Create your models here.


class It(models.Model):
    # 接口项目表
    it_name = models.CharField(max_length=64, default='', verbose_name='项目名称')
    it_desc = models.CharField(max_length=256, default='', verbose_name='项目描述')
    it_start_time = models.DateField(verbose_name='项目开始时间')
    it_end_time = models.DateField(verbose_name='项目结束时间')

    def __str__(self):
        return self.it_name



    def xxoo(self):

        if self.api_set.count():
            result = self.api_set.filter(api_pass_status=1).count() / self.api_set.count() *100
            # print(self.api_set.count(),self.api_set.filter(api_pass_status=1).count(),self.it_name,result)
            return "%.2f%%" % (result)
        else:
            return 0

class Api(models.Model):
    # 项目测试用例
    api_sub_it= models.ForeignKey(to='It',on_delete=models.CASCADE , verbose_name='所属接口项目')
    api_name = models.CharField(max_length=32, default='', verbose_name='用例名称')
    api_desc = models.CharField(max_length=255, default='', verbose_name='用例描述')
    api_url = models.CharField(max_length=255, default='', verbose_name='请求的url')
    api_method = models.CharField(max_length=32, default='', verbose_name='请求的类型')
    api_params = models.CharField(max_length=255, default={}, verbose_name='请求的参数')
    api_data = models.CharField(max_length=255, default={}, verbose_name='请求的data')
    api_exprct = models.CharField(max_length=4196, default={}, verbose_name='预期结果')
    api_report = models.TextField(verbose_name='报告',default='')
    api_run_time = models.DateTimeField(null=True, verbose_name='执行时间')
    api_pass_status_choices = (
        (0, '未通过'),
        (1, '已通过'),
    )
    api_pass_status = models.IntegerField(choices=api_pass_status_choices, verbose_name='执行是否通过',default=0)
    api_run_status_choices = (
        (0, '未执行'),
        (1, '已执行')
    )
    api_run_status = models.IntegerField(choices=api_run_status_choices, verbose_name='是否执行',default=0)

    def __str__(self):
        return self.api_name

class Logs(models.Model):
    '''用例执行记录
        1.所属项目
        2.执行时间
        3.执行的测试报告
        4.通过多少，失败多少，共执行多少，通过率
    '''
    log_report=models.TextField(verbose_name='报告',default='')
    log_sub_it = models.ForeignKey(to='It',on_delete=models.CASCADE, verbose_name='所属接口的项目')
    log_run_time=models.DateTimeField(null=True,verbose_name='log日志产生时间',auto_now_add=True)
    log_pass_count = models.IntegerField(verbose_name='通过数量')
    log_failed_count = models.IntegerField(verbose_name='失败数量')
    log_errors_count = models.IntegerField(verbose_name='报错数量')
    log_run_count = models.IntegerField(verbose_name='执行用例总数量')


    def pass_rate(self):
        '''通过率'''
        if self.log_run_count:
            result = self.log_pass_count / self.log_run_count * 100
            if result:
                return "%.f%%" % (result)
            else:
                return 0
        else:
            return 0

    class Meta:
        ordering=['-log_run_time']

templates/add_api.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="{% url "index" %}">首页</a></li>
        <li class="breadcrumb-item active">{{ it_obj.it_name }}</li>
        <li class="breadcrumb-item active">添加用例</li>
    </ol>
{% endblock %}

{% block content %}

    <form action=""  method="post" novalidate>
        {% csrf_token %}
        {% for foo in api_form_obj %}

            <div>
                <label for="{{ item.id_for_label }}">{{ foo.label }}</label>
                {{ foo }}
            </div>
            <div><span style="color: red;" >{{ foo.errors.0 }}</span></div>


        {% endfor %}
        <input type="submit" class="btn btn-success" value="提交">
    </form>
{% endblock %}

templates/add_it.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="{% url "index" %}">首页</a></li>
        <li class="breadcrumb-item active">项目列表</li>
        <li class="breadcrumb-item active">项目添加</li>
    </ol>
{% endblock %}
+
{% block content %}

    <form action=""  method="post" novalidate>
    {% csrf_token %}
        {% for foo in it_form_obj %}
            <label for="{{ item.id_for_label }}">{{ foo.label }}</label>
            <div>
                {{ foo }}
            </div>
            <div><span style="color: red;" >{{ foo.errors.0 }}</span></div>


        {% endfor %}
        <input type="submit" class="btn btn-success" value="提交">
    </form>

{% endblock %}

templates/api_list.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="{% url "index" %}">首页</a></li>
        <li class="breadcrumb-item">{{ it_obj.it_name }}</li>
        <li class="breadcrumb-item">用例列表</li>

    </ol>
{% endblock %}

{% block content %}

    {#    {% if it_obj %}#}
    <div class="card card-primary card-outline">
        {#                <div class="card-header">#}
        {#                    <a href="">添加用例</a>#}
        {#                </div>#}

        <table class="table table-striped table-hover table-bordered ">
            {#                <div class="card-header">#}
            {#                    <a href="">添加用例</a>#}
            {#                </div>#}
            <thead>
            <tr>
                <th>选择</th>
                <th>序号</th>
                <th>用例名称</th>
                <th>描述</th>
                <th>请求url</th>
                <th>请求类型</th>
                <th>请求参数</th>
                <th>预期值</th>
                <th>用例报告</th>
                <th>通过状态</th>
                <th>是否执行</th>
                <td>操作</td>
            </tr>
            </thead>

            <tbody>
            <tr>
                {% for foo in api_obj %}
                    <tr>
                        <td>
                            <input type="checkbox" value="{{ foo.pk }}" name="checkbox_list">
                        </td>
                        <td>{{ forloop.counter }}</td>
                        <td title="{{ foo.api_name }}">{{ foo.api_name |slice:'10' }}</td>
                        <td title="{{ foo.api_desc }}">{{ foo.api_desc |slice:'10' }}</td>
                        <td title="{{ foo.api_url }}">{{ foo.api_url|truncatechars:10 }}</td>
                        <td title="{{ foo.api_method }}">{{ foo.api_method |slice:'15' }}</td>
                        <td title="{{ foo.api_params }}">{{ foo.api_params |truncatechars:10 }}</td>
                        <td title="{{ foo.api_exprct }}">{{ foo.api_exprct |truncatechars:10 }}</td>
                        {% if  foo.api_report %}
                            <td><a href="{% url 'download_case_report' foo.pk %}">下载</a></td>
                        {% else %}
                            <td>无</td>
                        {% endif %}
                        <td>{{ foo.get_api_pass_status_display }}</td>
                        <td>{{ foo.get_api_run_status_display }}</td>
                        <td>
                            <a href="{% url 'edit_api' foo.pk %}" class="btn btn-success btn-sm">编辑</a>
                            <a href="{% url 'delete_api' foo.pk %}" class="btn btn-danger btn-sm">删除</a>
                            <a href="{% url 'api_run' foo.pk %}" class="btn btn-secondary btn-sm">执行</a>
                            {#                                    <a href="" class="btn btn-secondary btn-sm">实验</a>#}
                        </td>

                    </tr>
                {% endfor %}

            </tr>
            </tbody>

        </table>
        <div>
        {% csrf_token %}
            <input type="button" class="btn btn-success" value="批量执行" id="exeute">
        </div>
    </div>

    {#    {% else %}#}
    {#        没有数据，去 <a href="{% url 'add_api' %}">创建</a>#}
    {#    {% endif %}#}
{% endblock %}

{% block js %}
    <script src="https://cdn.bootcdn.net/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script>
        /*批量执行逻辑
        1.点击执行按钮，获取到所有选中的checkbox的值
            -点击后，没有找到选中的checkbox 要给提示信息
        2.将多个值发送到后端
        3.后端处理完毕，返回前端状态
         */
        $('#exeute').click(function () {
            var chk_value = new Array();
                $.each($('input[name="checkbox_list"]:checked'), function (index ,item) {//遍历，将所有选中的值放到数组中
                console.log(item, index);
                chk_value.push($(item).val());
            });

                if (chk_value.length==0) {
                    swal({
                        "title":'你还没有选中任何内容'
                    })

                }else {
                    console.log(111111111,chk_value);
                    //ajax将参数传递给后端
                    $.ajax({
                        "url":"{% url 'api_run' 0  %}",
                        "type":"POST",
                        "data":{"chk_value":JSON.stringify(chk_value),"csfmiddlewaretoken":$("[name='csfmiddlewaretoken']").val()},
                        success:function (data) {
                            //console.log(data)
                            window.location = data['path']

                        }
                    })
                }

        });
    </script>
{% endblock %}

templates/api_run.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="{% url "index" %}">首页</a></li>
        <li class="breadcrumb-item active">{{ it_obj.it_name }}</li>
        <li class="breadcrumb-item active">执行用例</li>
    </ol>
{% endblock %}

{% block content %}

    <form action=""  method="post" novalidate>
        {% csrf_token %}
        {% for foo in api_form_obj %}

            <div>
                <label for="{{ item.id_for_label }}">{{ foo.label }}</label>
                {{ foo }}
            </div>
            <div><span style="color: red;" >{{ foo.errors.0 }}</span></div>


        {% endfor %}
        <input type="submit" class="btn btn-success" value="提交">
    </form>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="{% url "index" %}">首页</a></li>
        <li class="breadcrumb-item active">项目列表</li>
        <li class="breadcrumb-item active">项目添加</li>
    </ol>
{% endblock %}

{% block content-head %}

{% endblock %}


{% block content %}

    <form action=""  method="post" novalidate>
    {% csrf_token %}
        {% for foo in it_form_obj %}
            <label for="{{ item.id_for_label }}">{{ foo.label }}</label>
            <div>
                {{ foo }}
            </div>
            <div><span style="color: red;" >{{ foo.errors.0 }}</span></div>


        {% endfor %}
        <input type="submit" class="btn btn-success" value="提交">
    </form>

{% endblock %}

templates/edit_api.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="{% url "index" %}">首页</a></li>
        <li class="breadcrumb-item"><a href="">用例列表</a></li>
{#        <li class="breadcrumb-item active"><a href="{% url "api_list/pk" %}">{{ api_obj.api_name }}</a></li>#}
        <li class="breadcrumb-item active">用例编辑</li>
    </ol>
{% endblock %}

{% block content-head %}

{% endblock %}


{% block content %}

    <form action=""  method="post" novalidate>
    {% csrf_token %}
        {% for foo in api_form_obj %}
            <label for="{{ item.id_for_label }}">{{ foo.label }}</label>
            <div>
                {{ foo }}
            </div>
            <div><span style="color: red;" >{{ foo.errors.0 }}</span></div>


        {% endfor %}
        <input type="submit" class="btn btn-success" value="提交">
    </form>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="{% url "index" %}">首页</a></li>
        <li class="breadcrumb-item active">项目列表</li>
    </ol>
{% endblock %}

{% block content %}

    {% if it_obj %}
        <div class="card card-primary card-outline">


            <table class="table table-striped table-hover table-bordered ">
                <div class="card-header">
                    <a href="{% url 'add_it' %}">添加项目</a>
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>描述</th>
                        <th>开始时间</th>
                        <th>结束时间</th>
                        <th>用例数据</th>
                        <th>覆盖率</th>
                        <th>操作</th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        {% for foo in it_obj %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ foo.it_name }}</td>
                                <td>{{ foo.it_desc }}</td>
                                <td>{{ foo.it_start_time.isoformat }}</td>
                                <td>{{ foo.it_end_time.isoformat }}</td>
                                <td>{{ foo.api_set.count }}</td>
                                <td>{{ foo.xxoo }}</td>
                                <td>
                                    <a href="{% url 'edit_it' foo.pk %}" class="btn btn-success btn-sm" >编辑</a>
                                    <a href="{% url 'delete_it' foo.pk %}" class="btn btn-danger btn-sm">删除</a>
                                    <a href="{% url 'add_api' foo.pk %}" class="btn btn-info btn-sm">添加用例</a>
                                    <a href="{% url 'api_list' foo.pk %}" class="btn btn-dark btn-sm">查看用例列表</a>
                                    <a href="{% url 'api_run' foo.pk %}" class="btn btn-secondary btn-sm">执行</a>
                                </td>

                            </tr>
                        {% endfor %}

                    </tr>
                    </tbody>
                </div>
            </table>
        </div>

    {% else %}
        没有数据，去 <a href="{% url 'add_it' %}">创建</a>
    {% endif %}
{% endblock %}

templates/logs_list.html
{% extends 'base.html' %}


{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item">Log日志</li>
{#        <li class="breadcrumb-item active">项目列表</li>#}
    </ol>
{% endblock %}


{% block content %}

    {#    {% if it_obj %}#}
    <div class="card card-primary card-outline">
        {#                <div class="card-header">#}
        {#                    <a href="">添加用例</a>#}
        {#                </div>#}

        <table class="table table-striped table-hover table-bordered ">
            {#                <div class="card-header">#}
            {#                    <a href="">添加用例</a>#}
            {#                </div>#}
            <thead>
            <tr>
                <th>序号</th>
                <th>所属项目</th>
                <th>创建时间</th>
                <th>用例失败数量</th>
                <th>用例报错数量</th>
                <th>用例通过数量</th>
                <th>用例总数量</th>
                <th>通过率</th>
                <th>用例报告</th>
            </tr>
            </thead>
            <tbody>
            {% for foo in logs_data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ foo.log_sub_it.it_name }}</td>
                    <td>{{ foo.log_run_time | date:"Y年m月d日 H时i分s秒"}}</td>
                    <td>{{ foo.log_failed_count }}</td>
                    <td>{{ foo.log_errors_count }}</td>
                    <td>{{ foo.log_pass_count }}</td>
                    <td>{{ foo.log_run_count }}</td>
                    <td>{{ foo.pass_rate }}</td>
                    <td><a href="{% url 'report_order' foo.pk %}">预览</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/report_order.html
{% extends 'base.html' %}


{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item active"><a href="{% url "logs_list" %}" class="btn btn-default">返回上一页</a></li>
        {#        <li class="breadcrumb-item active">项目列表</li>#}

    </ol>

{% endblock %}

{% block content %}

    <div class="card card-primary ">
        <div class="card-header">
            <h3 class="card-title">[{{ logs_data.log_run_time |date:"c" }}]创建的用力报告</h3>
        </div>
        <div class="card-body">
            <div class="chart">
                <div style="min-height: 650px;height: 100%;max-height: 450px;max-width: 100%;">
                    {{ logs_data.log_report | safe }}
                </div>
            </div>
            <div>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="text" name="report_pk" value="{{ logs_data.pk }} " hidden>
                    <input type="submit" class="btn btn-success" value="下载报告">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/show_tab.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">用例通过相关</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="chart">
                <div id="areaChart"
                        style="min-height: 250px; height: 450px; max-height: 450px; max-width: 100%;"></div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
{% endblock %}



{% block js %}

    <script src="{% static 'echarts.min.js' %}"></script>
    <script>
        function pie(title,data){
            //1.实例化 echarts 对象
        PieObj =echarts.init(document.getElementById("areaChart"));
        //2.
        PieObjoption = {
            title: {
                text: title,
                subtext: '最新一次用例执行',
                left: 'center'
            },
            tooltip: {
                trigger: 'item'
            },
            legend: {
                orient: 'vertical',
                left: 'left',

            },
            series: [
                {
                    name: '测试用例',
                    type: 'pie',
                    radius: '50%',
                    data: data,
                    emphasis: {
                        itemStyle: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0,0,0,0.5)'
                        }
                    }
                }
            ]
        };
        //3.
        PieObj.setOption(PieObjoption);
        }

        function init(){
            $.ajax({
                "url":{% url 'show_tab' %},
                "type":"POST",
                "data":{},
                success:function (data) {
                    console.log('1111111')
                    pie(data['pie']['title'],data['pie']['data'])
                }
            })
        }

        init()
    </script>
{% endblock %}

templates/xrm_list.html
{% extends 'base.html' %}


{% block breadcrumb %}
    <ol class="breadcrumb ">
        <li class="breadcrumb-item">西人马项目列表</li>
{#        <li class="breadcrumb-item active">项目列表</li>#}
    </ol>
{% endblock %}


{% block content %}
    <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>塔斯云3.0</h3>

                  <a href="http://172.28.2.45:8080/login" target="_blank" class="btn-bottom" id="">测试环境</a>
                  <a href="http://oliver.fatritech.com/login" target="_blank" class="btn-bottom" id="">生产环境</a>
                <p> </p>
              </div>
              <div class="icon">
{#                <i class="fas fa-shopping-cart"></i>#}
                <i class="fas fa-shopping-basket"></i>
              </div>
              <a href="#" class="small-box-footer">
                More info <i class="fas fa-arrow-circle-right"></i>
              </a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>沙钢<sup style="font-size: 20px"></sup></h3>

                <p>Bounce Rate</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">
                More info <i class="fas fa-arrow-circle-right"></i>
              </a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>梯联网</h3>

                <p>User Registrations</p>
              </div>
              <div class="icon">
                <i class="fas fa-user-plus"></i>
              </div>
              <a href="#" class="small-box-footer">
                More info <i class="fas fa-arrow-circle-right"></i>
              </a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>利欧泵业</h3>

                <p>Unique Visitors</p>
              </div>
              <div class="icon">
                <i class="fas fa-chart-pie"></i>
              </div>
              <a href="#" class="small-box-footer">
                More info <i class="fas fa-arrow-circle-right"></i>
              </a>
            </div>
          </div>
          <!-- ./col -->
        </div>
{% endblock %}

{% block js %}
    <script>
        $('#test_taas').click(function () {
            alert('http://172.28.2.45:8080')
        })
    </script>

{% endblock %}